name: "Deploy OpenRuntimes Images"

on:
  workflow_run:
    workflows: ["Build OpenRuntimes Images"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Flutter
          - ID: flutter-3.24
            RUNTIME: flutter
            VERSION: "3.24"
            IMAGE: openruntimes/flutter
          - ID: flutter-3.27
            RUNTIME: flutter
            VERSION: "3.27"
            IMAGE: openruntimes/flutter
          - ID: flutter-3.29
            RUNTIME: flutter
            VERSION: "3.29"
            IMAGE: openruntimes/flutter
          - ID: flutter-3.32
            RUNTIME: flutter
            VERSION: "3.32"
            IMAGE: openruntimes/flutter

          # Static
          - ID: static-1
            RUNTIME: static
            VERSION: "1"
            IMAGE: openruntimes/static

          # Node
          - ID: node-22.js
            RUNTIME: node
            VERSION: "22"
            IMAGE: openruntimes/node
          - ID: node-21.js
            RUNTIME: node
            VERSION: "21.0"
            IMAGE: openruntimes/node
          - ID: node-20.js
            RUNTIME: node
            VERSION: "20.0"
            IMAGE: openruntimes/node
          - ID: node-19.js
            RUNTIME: node
            VERSION: "19.0"
            IMAGE: openruntimes/node
          - ID: node-18.js
            RUNTIME: node
            VERSION: "18.0"
            IMAGE: openruntimes/node
          - ID: node-16.js
            RUNTIME: node
            VERSION: "16.0"
            IMAGE: openruntimes/node
          - ID: node-14.5.js
            RUNTIME: node
            VERSION: "14.5"
            IMAGE: openruntimes/node

          # Deno
          - ID: deno-2.0
            RUNTIME: deno
            VERSION: "2.0"
            IMAGE: openruntimes/deno
          - ID: deno-1.46
            RUNTIME: deno
            VERSION: "1.46"
            IMAGE: openruntimes/deno
          - ID: deno-1.40
            RUNTIME: deno
            VERSION: "1.40"
            IMAGE: openruntimes/deno
          - ID: deno-1.35
            RUNTIME: deno
            VERSION: "1.35"
            IMAGE: openruntimes/deno
          - ID: deno-1.24
            RUNTIME: deno
            VERSION: "1.24"
            IMAGE: openruntimes/deno
          - ID: deno-1.21
            RUNTIME: deno
            VERSION: "1.21"
            IMAGE: openruntimes/deno

          # Python
          - ID: python-3.12
            RUNTIME: python
            VERSION: "3.12"
            IMAGE: openruntimes/python
          - ID: python-3.11
            RUNTIME: python
            VERSION: "3.11"
            IMAGE: openruntimes/python
          - ID: python-3.10
            RUNTIME: python
            VERSION: "3.10"
            IMAGE: openruntimes/python
          - ID: python-3.9
            RUNTIME: python
            VERSION: "3.9"
            IMAGE: openruntimes/python
          - ID: python-3.8
            RUNTIME: python
            VERSION: "3.8"
            IMAGE: openruntimes/python

          # Python ML
          - ID: python-ml-3.12
            RUNTIME: python
            VERSION: "ml-3.12"
            IMAGE: openruntimes/python-ml
          - ID: python-ml-3.11
            RUNTIME: python
            VERSION: "ml-3.11"
            IMAGE: openruntimes/python-ml

          # Dart
          - ID: dart-3.8
            RUNTIME: dart
            VERSION: "3.8"
            IMAGE: openruntimes/dart
          - ID: dart-3.5
            RUNTIME: dart
            VERSION: "3.5"
            IMAGE: openruntimes/dart
          - ID: dart-3.3
            RUNTIME: dart
            VERSION: "3.3"
            IMAGE: openruntimes/dart
          - ID: dart-3.1
            RUNTIME: dart
            VERSION: "3.1"
            IMAGE: openruntimes/dart
          - ID: dart-3.0
            RUNTIME: dart
            VERSION: "3.0"
            IMAGE: openruntimes/dart
          - ID: dart-2.19
            RUNTIME: dart
            VERSION: "2.19"
            IMAGE: openruntimes/dart
          - ID: dart-2.18
            RUNTIME: dart
            VERSION: "2.18"
            IMAGE: openruntimes/dart
          - ID: dart-2.17
            RUNTIME: dart
            VERSION: "2.17"
            IMAGE: openruntimes/dart
          - ID: dart-2.16
            RUNTIME: dart
            VERSION: "2.16"
            IMAGE: openruntimes/dart
          - ID: dart-2.15
            RUNTIME: dart
            VERSION: "2.15"
            IMAGE: openruntimes/dart

          # Ruby
          - ID: ruby-3.3
            RUNTIME: ruby
            VERSION: "3.3"
            IMAGE: openruntimes/ruby
          - ID: ruby-3.2
            RUNTIME: ruby
            VERSION: "3.2"
            IMAGE: openruntimes/ruby
          - ID: ruby-3.1
            RUNTIME: ruby
            VERSION: "3.1"
            IMAGE: openruntimes/ruby
          - ID: ruby-3.0
            RUNTIME: ruby
            VERSION: "3.0"
            IMAGE: openruntimes/ruby

          # PHP
          - ID: php-8.3
            RUNTIME: php
            VERSION: "8.3"
            IMAGE: openruntimes/php
          - ID: php-8.2
            RUNTIME: php
            VERSION: "8.2"
            IMAGE: openruntimes/php
          - ID: php-8.1
            RUNTIME: php
            VERSION: "8.1"
            IMAGE: openruntimes/php
          - ID: php-8.0
            RUNTIME: php
            VERSION: "8.0"
            IMAGE: openruntimes/php

          # Swift
          - ID: swift-5.10
            RUNTIME: swift
            VERSION: "5.10"
            IMAGE: openruntimes/swift
          - ID: swift-5.9
            RUNTIME: swift
            VERSION: "5.9"
            IMAGE: openruntimes/swift
          - ID: swift-5.8
            RUNTIME: swift
            VERSION: "5.8"
            IMAGE: openruntimes/swift

          # Kotlin
          - ID: kotlin-2.0
            RUNTIME: kotlin
            VERSION: "2.0"
            IMAGE: openruntimes/kotlin
          - ID: kotlin-1.9
            RUNTIME: kotlin
            VERSION: "1.9"
            IMAGE: openruntimes/kotlin
          - ID: kotlin-1.8
            RUNTIME: kotlin
            VERSION: "1.8"
            IMAGE: openruntimes/kotlin
          - ID: kotlin-1.6
            RUNTIME: kotlin
            VERSION: "1.6"
            IMAGE: openruntimes/kotlin

          # Java
          - ID: java-22
            RUNTIME: java
            VERSION: "22"
            IMAGE: openruntimes/java
          - ID: java-21.0
            RUNTIME: java
            VERSION: "21.0"
            IMAGE: openruntimes/java
          - ID: java-18.0
            RUNTIME: java
            VERSION: "18.0"
            IMAGE: openruntimes/java
          - ID: java-17.0
            RUNTIME: java
            VERSION: "17.0"
            IMAGE: openruntimes/java
          - ID: java-11.0
            RUNTIME: java
            VERSION: "11.0"
            IMAGE: openruntimes/java
          - ID: java-8.0
            RUNTIME: java
            VERSION: "8.0"
            IMAGE: openruntimes/java

          # C++
          - ID: cpp-20
            RUNTIME: cpp
            VERSION: "20"
            IMAGE: openruntimes/cpp
          - ID: cpp-17
            RUNTIME: cpp
            VERSION: "17"
            IMAGE: openruntimes/cpp

          # Dotnet
          - ID: dotnet-8.0
            RUNTIME: dotnet
            VERSION: "8.0"
            IMAGE: openruntimes/dotnet
          - ID: dotnet-7.0
            RUNTIME: dotnet
            VERSION: "7.0"
            IMAGE: openruntimes/dotnet
          - ID: dotnet-6.0
            RUNTIME: dotnet
            VERSION: "6.0"
            IMAGE: openruntimes/dotnet

          # Bun
          - ID: bun-1.1
            RUNTIME: bun
            VERSION: "1.1"
            IMAGE: openruntimes/bun
          - ID: bun-1.0
            RUNTIME: bun
            VERSION: "1.0"
            IMAGE: openruntimes/bun

          # Go
          - ID: go-1.23
            RUNTIME: go
            VERSION: "1.23"
            IMAGE: openruntimes/go
    name: ${{ matrix.ID }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Build Commit SHA
        id: get-sha
        run: |
          echo "sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
      
      - name: Create Version Tags
        run: |
          # Pull the commit-hash tagged image
          docker pull ${{ matrix.IMAGE }}:${{ steps.get-sha.outputs.sha }}
          
          # Create version tags
          docker tag ${{ matrix.IMAGE }}:${{ steps.get-sha.outputs.sha }} ${{ matrix.IMAGE }}:v5-${{ matrix.VERSION }}
          docker tag ${{ matrix.IMAGE }}:${{ steps.get-sha.outputs.sha }} ${{ matrix.IMAGE }}:latest
          
          # Push version tags
          docker push ${{ matrix.IMAGE }}:v5-${{ matrix.VERSION }}
          docker push ${{ matrix.IMAGE }}:latest
      
      - name: Verify Rollback Capability
        run: |
          # Test that we can pull the specific commit hash
          docker pull ${{ matrix.IMAGE }}:${{ steps.get-sha.outputs.sha }}
          echo "Rollback capability verified for ${{ matrix.IMAGE }}:${{ steps.get-sha.outputs.sha }}" 